// Code generated by "stringer -type=Enum"; DO NOT EDIT.

package IPVersion

import "strconv"

const (
	_Enum_name_0 = "IPv4"
	_Enum_name_1 = "IPv6"
)

func (i Enum) String() string {
	switch {
	case i == 4:
		return _Enum_name_0
	case i == 6:
		return _Enum_name_1
	default:
		return "Enum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
